services:
  node1:
    build: .
    command:
      [
        "--nodeid", "node1",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8001:8000"
    networks: ["raftnetwork"]
    volumes:
      - shared_data:/var/lib/thesis
      - ./clusterConfig3.json:/config/clusterConfig.json
    # environment:
    #   THESIS_HTTP_HOST: "127.0.0.1"
    #   THESIS_INTERNAL_HTTP_PORT: "8000"
    #   THESIS_EXTERNAL_HTTP_PORT: "8000"

  node2:
    build: .
    command:
      [
        "--nodeid", "node2",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8002:8000"
    networks: ["raftnetwork"]
    volumes:
      - shared_data:/var/lib/thesis
      - ./clusterConfig3.json:/config/clusterConfig.json

  node3:
    build: .
    command:
      [
        "--nodeid", "node3",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8003:8000"
    networks: ["raftnetwork"]
    volumes:
      - shared_data:/var/lib/thesis
      - ./clusterConfig3.json:/config/clusterConfig.json

networks:
  raftnetwork:

volumes:
  shared_data: