services:
  node1:
    image: kave:latest
    command: "--config=/config/clusterConfig.json"
    ports:
      - "8001:8000"
    networks: ["raftnetwork"]
    volumes:
      - node1_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json
    environment:
      - NODE_ID=node1
      - RAFT_PORT=7000
      - HTTP_PORT=8000
      - BOOTSTRAP=TRUE
      - PUBLIC_HTTP_HOST=localhost

  node2:
    image: kave:latest
    command: "--config=/config/clusterConfig.json"
    ports:
      - "8002:8000"
    networks: ["raftnetwork"]
    volumes:
      - node2_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json
    environment:
      - NODE_ID=node2
      - RAFT_PORT=7000
      - HTTP_PORT=8000
      - PUBLIC_HTTP_HOST=localhost

  node3:
    image: kave:latest
    command: "--config=/config/clusterConfig.json"
    ports:
      - "8003:8000"
    networks: ["raftnetwork"]
    volumes:
      - node3_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json
    environment:
      - NODE_ID=node3
      - RAFT_PORT=7000
      - HTTP_PORT=8000
      - PUBLIC_HTTP_HOST=localhost

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks: ["raftnetwork"]
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: ["raftnetwork"]
    depends_on:
      - prometheus

networks:
  raftnetwork:

volumes:
  node1_volume:
  node2_volume:
  node3_volume: