services:
  node1:
    image: thesis_node_image:latest
    command:
      [
        "--nodeid", "node1",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8001:8000"
    networks: ["raftnetwork"]
    volumes:
      - node1_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json

  node2:
    image: thesis_node_image:latest
    command:
      [
        "--nodeid", "node2",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8002:8000"
    networks: ["raftnetwork"]
    volumes:
      - node2_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json

  node3:
    image: thesis_node_image:latest
    command:
      [
        "--nodeid", "node3",
        "--config", "/config/clusterConfig.json"
      ]
    ports:
      - "8003:8000"
    networks: ["raftnetwork"]
    volumes:
      - node3_volume:/data
      - ./config/clusterConfig3.json:/config/clusterConfig.json

networks:
  raftnetwork:

volumes:
  node1_volume:
  node2_volume:
  node3_volume: