package ot

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/binary"
	"errors"
	"fmt"
	"time"
)

const (
	nonceSize     int = 12
	timestampSize int = 8
	scalarSize    int = 32 // Size of scalar, the ephemeral key generated by the server, in bytes (matching Ristretto255 scalars)
	gcmTagSize    int = 16
	TokenSize     int = nonceSize + scalarSize + timestampSize + gcmTagSize

	// Size of the cluster key in bytes (32 enables AES-256)
	ClusterKeySize int = 32
	// Default time-to-live for tokens in seconds
	DefaultTokenTTL int64 = 30
)

var (
	ErrInvalidClusterKeySize = fmt.Errorf("token_codec error: invalid cluster key size, expected %d", ClusterKeySize)
	ErrInvalidScalarSize     = fmt.Errorf("token_codec error: invalid scalar size, expected %d", scalarSize)
	ErrInvalidTokenSize      = errors.New("token_codec error: invalid token sized")
	ErrTokenExpired          = errors.New("token_codec error: token has expired")
	ErrTokenTampered         = errors.New("token_codec error: decrypting token failed (tampered or wrong key)")
	ErrPlaintextCorrupted    = errors.New("token_codec error: decrypting token plaintext with unexpected size")
)

// RandomKey256 creates a cryptographically secure 32 byte key,
// or crashes the program on failure
func RandomKey256() []byte {
	key := make([]byte, ClusterKeySize)
	_, _ = rand.Read(key) // never returns error, only panics
	return key
}

// newTokenCodec creates a new token codec with the supplied clusterKey and ttl in seconds.
// If the ttl is negative or above the maximum allowed ttl, [DefaultTokenTTL] is used
func newTokenCodec(clusterKey []byte, ttl int64) (*tokenCodec, error) {
	if len(clusterKey) != ClusterKeySize {
		return nil, ErrInvalidClusterKeySize
	}

	block, err := aes.NewCipher(clusterKey)
	if err != nil {
		return nil, fmt.Errorf("token_codec error: failed to create cipher block: %w", err)
	}

	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("token_codec error: failed to create GCM: %w", err)
	}

	if ttl <= 0 || ttl > MaxTokenTTL {
		ttl = DefaultTokenTTL
	}

	return &tokenCodec{
		aead:   aead,
		maxTTL: time.Duration(ttl) * time.Second,
	}, nil
}

type tokenCodec struct {
	aead cipher.AEAD
	// maximum time-to-live for any key in seconds
	maxTTL time.Duration
}

// seal encrypts the scalar, the servers ephemeral key into a token
// The token layout in bytes:
//
//	[ Nonce (12) | Plaintext (ScalarSize=32 + sizeof(int64)) | GCM Tag (16) ]
//
// The plaintext that gets encrypted is:
//
//	[ ScalarSize (32 bytes) | timestamp (8 bytes, unix nanos as int64) ]
func (tc *tokenCodec) seal(scalar []byte) ([]byte, error) {
	if len(scalar) != scalarSize {
		return nil, ErrInvalidScalarSize
	}
	now := time.Now().UnixNano()
	timestamp := make([]byte, timestampSize)
	binary.BigEndian.PutUint64(timestamp, uint64(now))

	nonce := make([]byte, tc.aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, fmt.Errorf("token_codec error: seal failed: %w", err)
	}

	plaintext := make([]byte, 0, scalarSize+timestampSize)
	plaintext = append(plaintext, scalar...)
	plaintext = append(plaintext, timestamp...)
	token := tc.aead.Seal(nonce, nonce, plaintext, nil)
	return token, nil
}

// open decrypts the token into the original scalar, the servers ephemeral key.
// If the tokens length is not the expected length specified by TokenSize, it returns [ErrInvalidTokenSize]
// It checks if the tokens ttl has expired, and returns [ErrTokenExpired] if so, preventing replay attacks.
// If the tokens bits has been tampered with, GCM auth fails and it returns [ErrTokenTampered]
func (tc *tokenCodec) open(token []byte) (scalar []byte, err error) {
	if len(token) != TokenSize {
		return nil, ErrInvalidTokenSize
	}

	nonce := token[:nonceSize]
	ciphertext := token[nonceSize:]

	plaintext, err := tc.aead.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, ErrTokenTampered
	}

	if len(plaintext) != scalarSize+timestampSize {
		return nil, ErrPlaintextCorrupted
	}

	scalar = plaintext[:scalarSize]

	tsBytes := plaintext[scalarSize:]
	unixNanos := int64(binary.BigEndian.Uint64(tsBytes))
	timestamp := time.Unix(0, unixNanos)
	if time.Since(timestamp) > tc.maxTTL {
		return nil, ErrTokenExpired
	}

	return
}
