name: Deploy to Github Pages
description: Deploys the ui of the key-value store to github pages

inputs:
  cluster_url:
    required: true
    description: url of the k8s cluster, supplied to the frontend kv client
  kave_ot_slot_size:
    required: true
    description: slot size of the OT api 
  kave_ot_slot_count:
    required: true
    description: slot count of the OT api 
  admin_token:
    required: true
    description: admin token for protected admin routes

outputs:
  page_url:
    description: url of the deployed site
    value: ${{ steps.deploy-gh-pages.outputs.page_url }}

runs:
  using: composite
  steps:
    # - name: checkout should be done in the workflow prior to calling the action

    - name: Install bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: bun --cwd=./ui i

    - name: Build site
      env:
        BASE_PATH: "/${{ github.event.repository.name }}"
        VITE_KAVE_CLUSTER_URL: "${{ inputs.cluster_url }}"
        VITE_KAVE_OT_SLOT_SIZE: ${{ inputs.kave_ot_slot_size }}
        VITE_KAVE_OT_SLOT_COUNT: ${{ inputs.kave_ot_slot_count }}
        # still accessible from js bundle or headers, but at least randoms
        # wont nuke the site during demo
        VITE_KAVE_ADMIN_TOKEN: ${{ inputs.admin_token }}
      shell: bash
      run: bun --cwd=./ui run build

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v5
      with:
        path: "ui/build/"

    - name: Deploy to Github Pages        
      id: deploy-gh-pages
      uses: actions/deploy-pages@v5
        

