---
config:
  layout: elk
---
flowchart TB
    client([Client]):::plain --> ingress

    subgraph k8s_cluster["Kubernetes Cluster"]
        direction TB

        subgraph ingress_layer["Ingress Layer"]
            ingress[Traefik IngressRoute, Middleware]:::k8s
            pub_cert[(kave-public-tls\nCertificate)]:::plain
            ingress --> ext_svc
            ingress -.-> pub_cert
        end

        subgraph services["Internal Services"]
            ext_svc["kave-external Service (ClusterIP)"]:::k8s
            headless_svc["kave-headless Service (Headless, DNS)"]:::k8s
        end

        subgraph statefulset["StatefulSet:  3 voter pod"]
            direction LR
            p1["kave-voter-0"]:::k8s
            p2["kave-voter-1"]:::k8s
            p3["kave-voter-2"]:::k8s

            
            p1 <--> p2
            p2 <--> p3
            p1 <--> p3

           
            p1 -.-> pvc0[(PVC ~20Gi)]:::plain
            p2 -.-> pvc1[(PVC 20Gi)]:::plain
            p3 -.-> pvc2[(PVC 20Gi)]:::plain

            p1 -.-> cfg{{kave-config ConfigMap}}:::plain
            p2 -.-> cfg
            p3 -.-> cfg

            p1 -.-> raft_tls{{kave-raft-tls secrets}}:::plain
            p2 -.-> raft_tls
            p3 -.-> raft_tls

            
            %%subgraph init_flow["InitContainer: wait-for-dns"]
            %%    direction TB
            %%    check_dns["nslookup kave-voter-0"]:::plain
            %%    check_tcp["nc -z (check Raft port open)"]:::plain
            %%    proceed["Proceed with startup"]:::plain
            %%    check_dns --> check_tcp --> proceed
            %% end
           
            p2 -.-> init_flow
            p3 -.-> init_flow
        end

        %% Internal connectivity
        ext_svc --> p1 & p2 & p3
        headless_svc -.-> p1 & p2 & p3
    end

    subgraph cert_infra["kave cert-manager"]
        direction TB
        issuer_self["SelfSigned Issuer"]:::k8s
        issuer_ca["kave-ca-issuer (Internal CA)"]:::k8s
        issuer_letsencrypt["letsencrypt-prod ACME Issuer"]:::k8s
        issuer_self --> issuer_ca
        issuer_ca --> raft_tls
        issuer_letsencrypt --> pub_cert
    end

  
    pdb["PodDisruptionBudget (minAvailable = 2)"]:::plain
    netpol["NetworkPolicy to limit Raft access"]:::plain
    pdb -.-> statefulset
    netpol -.-> statefulset

    classDef plain fill:#acc6ff,stroke:#fff,stroke-width:4px,color:#000;
    classDef k8s fill:#326ce5,stroke:#fff,stroke-width:4px,color:#fff;
    classDef cluster fill:#fff,stroke:#bbb,stroke-width:2px,color:#326ce5;
    class client plain;
    class ingress,ext_svc,headless_svc,p1,p2,p3,issuer_self,issuer_ca,issuer_letsencrypt k8s;
    class k8s_cluster,ingress_layer,services,statefulset,cert_infra cluster;