name: Setup kubeconfig
description: Sets the kubeconfig config into the KUBECONFIG env var

inputs:
  kubeconfig_b64:
    description: Base64 encoded kubeconfig
    required: true

runs:
  using: composite
  steps:
    - name: Configure kube config
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig_b64 }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV