apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kave.name" . }}-config
  labels:
    {{- include "kave.labels" . | nindent 4 }}
data:
  clusterConfig.json: |
    {
      "log_level": {{  .Values.config.logLeve }},
      "checkpoint_interval_minutes": {{  .Values.config.checkpointIntervalMinutes }},
      "peer_discovery": {
        "mode": {{ .Values.config.peerDiscovery.mode }},
        "expected_count": {{ .Values.voters.replicas }}
      },
      "kv": {
        "kv_max_key_size": {{ .Values.config.kv.maxKeySize }},
        "kv_max_value_size": {{ .Values.config.kv.maxValueSize }}
      },
      "storage": {
          "storage_kind": {{  .Values.config.storage.kind }},
          "storage_data_dir": {{  .Values.config.storage.dataDir }}
      },
      "compaction": {
        "compaction_threshold": {{  .Values.config.compaction.threshold }},
        "compaction_interval_minutes": {{  .Values.config.compaction.intervalMinutes }},
        "compaction_max_rev_gap": {{  .Values.config.compaction.maxRevGap }}
      },
      "ot": {
        "ot_slot_count": {{ .Values.config.ot.slotCount }},
        "ot_slot_size": {{  .Values.config.ot.slotSize }},
        "ot_token_ttl": {{  .Values.config.ot.tokenTTL }}
      }
    }