# 1) Stable DNS name:
#    kave-voter-0.kave-headless.<namespace>.svc.cluster.local#

# 2) Stable storage
#   each pods PVC is reattached the same pod after restarts#

# 3) Ordered startup (podManagementPolicy: OrderedReady):
#   pods start one at 0 -> 1 -> 2 so pod 0 bootstraps
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kave.name" . }}-voter
  labels:
    {{- include "kave.labels" . | nindent 4 }}
    kave/role: voter
spec:
  serviceName: {{ .Values.serviceConfig.headlessService.name }}
  replicas: {{ .Values.voters.replicas }}
  # podManagementPolicy: OrderedReady
  podManagementPolicy: Parallel # needed otherwise kave-voter-0 will not see any other nodes during peer discovery
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kave.name" . }}
      kave/role: voter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kave.name" . }}
        kave/role: voter
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: {{ include "kave.name" . }}-config
        - name: raft-tls
          secret:
            secretName: {{ include "kave.name" . }}-raft-tls
      containers:
        - name: kave
          image: {{ include "kave.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/kave"
            - "--config=/config/clusterConfig.json"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_FQDN
              value: $(POD_NAME).{{ .Values.serviceConfig.headlessService.name }}.$(POD_NAMESPACE).svc.cluster.local
            - name: RAFT_PORT
              value: {{ .Values.ports.raft | quote }}
            - name: HTTP_PORT
              value: {{ .Values.ports.http | quote }}
            - name: NODE_ROLE
              value: voter
          ports:
            - name: raft
              containerPort: {{ .Values.ports.raft }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: kave-data
              mountPath: /data
            - name: config
              mountPath: /config
              readOnly: true
            - name: raft-tls
              mountPath: /tls/raft
              readOnly: true
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds }}
            failureThreshold: {{ .Values.healthcheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds }}
            failureThreshold: {{ .Values.healthcheck.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: kave-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
---
# network policy for extra security over mTLS:
# only pods from this statefulset (kave voters)
# can initiate connections on the voters 7000 port
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kave.name" . }}-raft-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kave.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kave.name" . }}
      kave/role: voter

  policyTypes:
    - Ingress

  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.ports.raft }}
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "kave.name" . }}
              kave/role: voter