image:
  repository: ghcr.io/balits/kave
  tag: ""
  pullPolicy: IfNotPresent

voters:
  replicas: 3

ports:
  raft: 7000
  http: 8000

config:
  logLevel: "debug"
  checkpointIntervalMinutes: 5
  peerDiscovery:
    mode: "dns"
  kv:
    maxKeySize: 512
    maxValueSize: 1024
  storage:
    kind: "boltdb"
    dataDir: "/data"
  compaction:
    threshold: 5
    intervalMinutes: 10
    maxRevGap: 10
  ot:
    slotCount: 32
    slotSize: 64
    tokenTTL: 60

storage:
  size: 1Gi
  storageClassName: "" # todo: might need to change on different platform

healthcheck:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3

pdb:
  minAvailable: 2 # for 3 voters

traefik:
  enabled: false # local cluster doesnt need it

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi