name: Test kave
description: Lint and format the code, then run unit and integration tests

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.11.4

    - name: Unit Tests
      shell: bash
      run: go test ./internal/... -race -count=1 --timeout 2m

    - name: Integration tests
      shell: bash
      # stress test are flaky on github runners, they are run
      # localy with --tags=stress
      run: go test ./test/integration/... -p 1 --timeout 10m | grep -v -E "Node stopped with error"