name: Wipe and Recreate Cluster

on:
  # only wipe cluster if really really needed,
  # only through manual dispatch
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11

      - name: Unit Tests
        run: go test ./internal/... -race -count=1

      # integration tests

  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: test 
    if:  github.event_name == 'workflow_dispatch' && (github.ref_name == 'main' || github.ref_name == 'feature/ci')
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # tag with short commit SHA (ghcr.io/balits/kave/:xyz123)
            type=sha,prefix=,format=short
            # + tag as latest
            type=raw,value=latest,enable=true
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # use GitHub Actions cache to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
      

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && (github.ref_name == 'main' || github.ref_name == 'feature/ci') 
    steps:
      - uses: actions/checkout@v4

      # - name: Setup K8s + Helm
      - uses: ./.github/actions/setup-helm-and-k8s
        with:
          kubeconfig_b64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Wipe cluster
        run: make wipe-recreate-cluster